In [33]:
import pandas as pd
from nltk import accuracy
from sklearn.metrics import classification_report

llama32_validated = pd.read_csv("Llama3.2-8b-label-validation-15 example.csv")
llama32_validated

,Unnamed: 0,Sentence,Result
0,0,Analyst : Do you run into any challenges with ...,"[Not Useful Class Diagram, Useful Use Case, Us..."
1,1,"AP : Actually , that is a constant source of c...","[Not Useful Class Diagram, Not Useful Use Case..."
2,2,"We have had several situations where , due to ...","[Not Useful Class Diagram, Not Useful Use Case..."
3,3,Analyst : Can you give me some examples of this ?,Here are 10 sentences with their corresponding...
4,4,AP :,"Verdict: \n[Not Useful Class Diagram, Useful U..."
...,...,...,...
140,140,HMO - funded patients are asked to make a copa...,"[Not Useful Class Diagram, Useful Use Case, No..."
141,141,Each patient also generates a reimbursement re...,"[Not Useful Class, Useful Use Case, Not Useful..."
142,142,Insurance companies and HMOs send their checks...,"[Not Useful Class Diagram, Useful Use Case, No..."
143,143,The clinic maintains a supplies inventory file...,"[Not Useful Class Diagram, Not Useful Use Case..."
144,144,Supplies and tools are stored in a standard la...,"[Not Useful Class Diagram, Not Useful Use Case..."

In [34]:
structure = []
usecase = []
activity = []
for index, item in llama32_validated.iterrows():
    try:
        if "Not Useful Class" in item["Result"]:
            structure.append(False)
        elif "Not Useful for Class" in item["Result"]:
            structure.append(False)
        else:
            structure.append(True)
        if "Not Useful Use Case" in item["Result"]:
            usecase.append(False)
        elif "Not Useful for Use Case" in item["Result"]:
            usecase.append(False)
        else:
            usecase.append(True)
        if "Not Useful Activity" in item["Result"]:
            activity.append(False)
        elif "Not Useful for Activity" in item["Result"]:
            activity.append(False)
        else:
            activity.append(True)
    except:
        structure.append(False)
        usecase.append(False)
        activity.append(False)

llama32_validated["structure"] = structure
llama32_validated["usecase"] = usecase
llama32_validated["activity"] = activity

In [35]:
llama32_validated

,Unnamed: 0,Sentence,Result,structure,usecase,activity
0,0,Analyst : Do you run into any challenges with ...,"[Not Useful Class Diagram, Useful Use Case, Us...",False,True,True
1,1,"AP : Actually , that is a constant source of c...","[Not Useful Class Diagram, Not Useful Use Case...",False,False,False
2,2,"We have had several situations where , due to ...","[Not Useful Class Diagram, Not Useful Use Case...",False,False,False
3,3,Analyst : Can you give me some examples of this ?,Here are 10 sentences with their corresponding...,False,False,False
4,4,AP :,"Verdict: \n[Not Useful Class Diagram, Useful U...",False,True,False
...,...,...,...,...,...,...
140,140,HMO - funded patients are asked to make a copa...,"[Not Useful Class Diagram, Useful Use Case, No...",False,True,False
141,141,Each patient also generates a reimbursement re...,"[Not Useful Class, Useful Use Case, Not Useful...",False,True,False
142,142,Insurance companies and HMOs send their checks...,"[Not Useful Class Diagram, Useful Use Case, No...",False,True,False
143,143,The clinic maintains a supplies inventory file...,"[Not Useful Class Diagram, Not Useful Use Case...",False,False,True
144,144,Supplies and tools are stored in a standard la...,"[Not Useful Class Diagram, Not Useful Use Case...",False,False,True

In [38]:
import pandas as pd
from sklearn.metrics import precision_score, recall_score, f1_score, accuracy_score

# Load ground truth and predictions
y_true = pd.read_csv("../type_classification-validation.csv")[["structure_focus"]]
y_pred = llama32_validated[["structure"]]

# Compute evaluation metrics
precision = precision_score(y_true, y_pred, average='macro')
recall = recall_score(y_true, y_pred, average='macro')
f1 = f1_score(y_true, y_pred, average='macro')
accuracy = accuracy_score(y_true, y_pred)

print(f"Precision: {precision:.4f}")
print(f"Recall: {recall:.4f}")
print(f"F1-score: {f1:.4f}")
print(f"Accuracy: {accuracy:.4f}")

Precision: 0.4353
Recall: 0.4435
F1-score: 0.3023
Accuracy: 0.3034