In [5]:
import pandas as pd
from nltk import accuracy
from sklearn.metrics import classification_report

llama32_validated = pd.read_csv("llama33-70b-instruct-q2_K-label-validation-5 example.csv")
llama32_validated

,Unnamed: 0,Sentence,Result
0,0,Analyst : Do you run into any challenges with ...,To determine the usefulness of the sentence fo...
1,1,"AP : Actually , that is a constant source of c...","Based on the sentence, I would classify it as:..."
2,2,"We have had several situations where , due to ...","Based on the sentence, I would classify it as:..."
3,3,Analyst : Can you give me some examples of this ?,"Here are some examples:\n\n1. ""A customer can ..."
4,4,AP :,It seems like you want me to classify a senten...
...,...,...,...
140,140,HMO - funded patients are asked to make a copa...,"Based on the sentence, I would classify it as:..."
141,141,Each patient also generates a reimbursement re...,"Based on the given sentence, I would classify ..."
142,142,Insurance companies and HMOs send their checks...,"Based on the given sentence, I would classify ..."
143,143,The clinic maintains a supplies inventory file...,"Based on the sentence, I would classify it as:..."
144,144,Supplies and tools are stored in a standard la...,"Based on the given sentence, I would classify ..."

In [6]:
structure = []
usecase = []
activity = []
for index, item in llama32_validated.iterrows():
    try:
        if "Not Useful Class" in item["Result"]:
            structure.append(False)
        elif "Not Useful for Class" in item["Result"]:
            structure.append(False)
        else:
            structure.append(True)
        if "Not Useful Use Case" in item["Result"]:
            usecase.append(False)
        elif "Not Useful for Use Case" in item["Result"]:
            usecase.append(False)
        else:
            usecase.append(True)
        if "Not Useful Activity" in item["Result"]:
            activity.append(False)
        elif "Not Useful for Activity" in item["Result"]:
            activity.append(False)
        else:
            activity.append(True)
    except:
        structure.append(False)
        usecase.append(False)
        activity.append(False)

llama32_validated["structure"] = structure
llama32_validated["usecase"] = usecase
llama32_validated["activity"] = activity

In [7]:
llama32_validated

,Unnamed: 0,Sentence,Result,structure,usecase,activity
0,0,Analyst : Do you run into any challenges with ...,To determine the usefulness of the sentence fo...,True,True,False
1,1,"AP : Actually , that is a constant source of c...","Based on the sentence, I would classify it as:...",False,False,False
2,2,"We have had several situations where , due to ...","Based on the sentence, I would classify it as:...",False,True,True
3,3,Analyst : Can you give me some examples of this ?,"Here are some examples:\n\n1. ""A customer can ...",False,False,False
4,4,AP :,It seems like you want me to classify a senten...,True,True,False
...,...,...,...,...,...,...
140,140,HMO - funded patients are asked to make a copa...,"Based on the sentence, I would classify it as:...",True,True,False
141,141,Each patient also generates a reimbursement re...,"Based on the given sentence, I would classify ...",True,True,True
142,142,Insurance companies and HMOs send their checks...,"Based on the given sentence, I would classify ...",False,True,True
143,143,The clinic maintains a supplies inventory file...,"Based on the sentence, I would classify it as:...",False,True,True
144,144,Supplies and tools are stored in a standard la...,"Based on the given sentence, I would classify ...",True,False,False

In [8]:
import pandas as pd
from sklearn.metrics import precision_score, recall_score, f1_score, accuracy_score

# Load ground truth and predictions
y_true = pd.read_csv("../type_classification-validation.csv")[["structure_focus"]]
y_pred = llama32_validated[["structure"]]

# Compute evaluation metrics
precision = precision_score(y_true, y_pred, average='macro')
recall = recall_score(y_true, y_pred, average='macro')
f1 = f1_score(y_true, y_pred, average='macro')
accuracy = accuracy_score(y_true, y_pred)

print(f"Precision: {precision:.4f}")
print(f"Recall: {recall:.4f}")
print(f"F1-score: {f1:.4f}")
print(f"Accuracy: {accuracy:.4f}")

Precision: 0.6520
Recall: 0.6818
F1-score: 0.6599
Accuracy: 0.7241