In [10]:
import pandas as pd
from nltk import accuracy
from sklearn.metrics import classification_report

r1_validated = pd.read_csv("DeepSeekR1-label-validation-10 example.csv")
r1_validated

,Unnamed: 0,index,Sentence,Result,Extracted
0,0,0,Analyst : Do you run into any challenges with ...,"<think>\nOkay, let's see. The user asked if th...","Useful Class, Useful Use Case, Not Useful Acti..."
1,1,1,"AP : Actually , that is a constant source of c...","<think>\nOkay, let's see. The user wants me to...","Not Useful Class, Not Useful Use Case, Not Use..."
2,2,2,"We have had several situations where , due to ...","<think>\nOkay, let's tackle this. The user wan...","Useful Class, Useful Use Case, Useful Activity"
3,3,3,Analyst : Can you give me some examples of this ?,"<think>\nOkay, let's tackle this query. The us...","Not Useful Class, Not Useful Use Case, Not Use..."
4,4,4,AP :,"<think>\nOkay, let's tackle this. The user pro...","Not Useful Class, Not Useful Use Case, Not Use..."
...,...,...,...,...,...
140,140,140,HMO - funded patients are asked to make a copa...,"<think>\nOkay, let's tackle this. The user wan...","Useful Class, Useful Use Case, Useful Activity"
141,141,141,Each patient also generates a reimbursement re...,"<think>\nOkay, let's tackle this new sentence:...","Useful Class, Useful Use Case, Not Useful Acti..."
142,142,142,Insurance companies and HMOs send their checks...,"<think>\nOkay, let's tackle this sentence: ""In...","Useful Class Diagram, Useful Use Case Diagram,..."
143,143,143,The clinic maintains a supplies inventory file...,"<think>\nOkay, let's break down the user's sen...","Useful Class, Useful Use Case, Useful Activity"
144,144,144,Supplies and tools are stored in a standard la...,"<think>\nOkay, let's tackle this sentence: ""Su...",NaN

In [11]:
structure = []
usecase = []
activity = []
for index, item in r1_validated.iterrows():
    try:
        if "Not Useful Class" in item["Extracted"]:
            structure.append(False)
        elif "Not Useful for Class" in item["Extracted"]:
            structure.append(False)
        else:
            structure.append(True)
        if "Not Useful Use Case" in item["Extracted"]:
            usecase.append(False)
        elif "Not Useful for Use Case" in item["Extracted"]:
            usecase.append(False)
        else:
            usecase.append(True)
        if "Not Useful Activity" in item["Extracted"]:
            activity.append(False)
        elif "Not Useful for Activity" in item["Extracted"]:
            activity.append(False)
        else:
            activity.append(True)
    except:
        structure.append(False)
        usecase.append(False)
        activity.append(False)

r1_validated["structure"] = structure
r1_validated["usecase"] = usecase
r1_validated["activity"] = activity

In [12]:
r1_validated

,Unnamed: 0,index,Sentence,Result,Extracted,structure,usecase,activity
0,0,0,Analyst : Do you run into any challenges with ...,"<think>\nOkay, let's see. The user asked if th...","Useful Class, Useful Use Case, Not Useful Acti...",True,True,False
1,1,1,"AP : Actually , that is a constant source of c...","<think>\nOkay, let's see. The user wants me to...","Not Useful Class, Not Useful Use Case, Not Use...",False,False,False
2,2,2,"We have had several situations where , due to ...","<think>\nOkay, let's tackle this. The user wan...","Useful Class, Useful Use Case, Useful Activity",True,True,True
3,3,3,Analyst : Can you give me some examples of this ?,"<think>\nOkay, let's tackle this query. The us...","Not Useful Class, Not Useful Use Case, Not Use...",False,False,False
4,4,4,AP :,"<think>\nOkay, let's tackle this. The user pro...","Not Useful Class, Not Useful Use Case, Not Use...",False,False,False
...,...,...,...,...,...,...,...,...
140,140,140,HMO - funded patients are asked to make a copa...,"<think>\nOkay, let's tackle this. The user wan...","Useful Class, Useful Use Case, Useful Activity",True,True,True
141,141,141,Each patient also generates a reimbursement re...,"<think>\nOkay, let's tackle this new sentence:...","Useful Class, Useful Use Case, Not Useful Acti...",True,True,False
142,142,142,Insurance companies and HMOs send their checks...,"<think>\nOkay, let's tackle this sentence: ""In...","Useful Class Diagram, Useful Use Case Diagram,...",True,True,True
143,143,143,The clinic maintains a supplies inventory file...,"<think>\nOkay, let's break down the user's sen...","Useful Class, Useful Use Case, Useful Activity",True,True,True
144,144,144,Supplies and tools are stored in a standard la...,"<think>\nOkay, let's tackle this sentence: ""Su...",NaN,False,False,False

In [17]:
import pandas as pd
from sklearn.metrics import precision_score, recall_score, f1_score, accuracy_score

# Load ground truth and predictions
y_true = pd.read_csv("../type_classification-validation.csv")[["structure_focus"]]
y_pred = r1_validated[["structure"]]

# Compute evaluation metrics
precision = precision_score(y_true, y_pred, average='macro')
recall = recall_score(y_true, y_pred, average='macro')
f1 = f1_score(y_true, y_pred, average='macro')
accuracy = accuracy_score(y_true, y_pred)

print(f"Precision: {precision:.4f}")
print(f"Recall: {recall:.4f}")
print(f"F1-score: {f1:.4f}")
print(f"Accuracy: {accuracy:.4f}")

Precision: 0.6683
Recall: 0.6312
F1-score: 0.6428
Accuracy: 0.7655

In [14]:
r1_validated

,Unnamed: 0,index,Sentence,Result,Extracted,structure,usecase,activity
0,0,0,Analyst : Do you run into any challenges with ...,"<think>\nOkay, let's see. The user asked if th...","Useful Class, Useful Use Case, Not Useful Acti...",True,True,False
1,1,1,"AP : Actually , that is a constant source of c...","<think>\nOkay, let's see. The user wants me to...","Not Useful Class, Not Useful Use Case, Not Use...",False,False,False
2,2,2,"We have had several situations where , due to ...","<think>\nOkay, let's tackle this. The user wan...","Useful Class, Useful Use Case, Useful Activity",True,True,True
3,3,3,Analyst : Can you give me some examples of this ?,"<think>\nOkay, let's tackle this query. The us...","Not Useful Class, Not Useful Use Case, Not Use...",False,False,False
4,4,4,AP :,"<think>\nOkay, let's tackle this. The user pro...","Not Useful Class, Not Useful Use Case, Not Use...",False,False,False
...,...,...,...,...,...,...,...,...
140,140,140,HMO - funded patients are asked to make a copa...,"<think>\nOkay, let's tackle this. The user wan...","Useful Class, Useful Use Case, Useful Activity",True,True,True
141,141,141,Each patient also generates a reimbursement re...,"<think>\nOkay, let's tackle this new sentence:...","Useful Class, Useful Use Case, Not Useful Acti...",True,True,False
142,142,142,Insurance companies and HMOs send their checks...,"<think>\nOkay, let's tackle this sentence: ""In...","Useful Class Diagram, Useful Use Case Diagram,...",True,True,True
143,143,143,The clinic maintains a supplies inventory file...,"<think>\nOkay, let's break down the user's sen...","Useful Class, Useful Use Case, Useful Activity",True,True,True
144,144,144,Supplies and tools are stored in a standard la...,"<think>\nOkay, let's tackle this sentence: ""Su...",NaN,False,False,False