In [25]:
import pandas as pd
from nltk import accuracy
from sklearn.metrics import classification_report

r1_validated = pd.read_csv("DeepSeekV3-label-validation-15 example.csv")
r1_validated

,Unnamed: 0,Sentence,Result
0,0,Analyst : Do you run into any challenges with ...,"[Useful for Class Diagram, Not Useful for Use ..."
1,1,"AP : Actually , that is a constant source of c...","[Not Useful Class, Not Useful Use Case, Not Us..."
2,2,"We have had several situations where , due to ...","[Useful Class, Useful Use Case, Not Useful Act..."
3,3,Analyst : Can you give me some examples of this ?,"[Useful Class, Useful Use Case, Not Useful Act..."
4,4,AP :,It seems like the sentence is incomplete. Coul...
...,...,...,...
140,140,HMO - funded patients are asked to make a copa...,"[Useful Class, Useful Use Case, Not Useful Act..."
141,141,Each patient also generates a reimbursement re...,"[Useful Class, Useful Use Case, Not Useful Act..."
142,142,Insurance companies and HMOs send their checks...,"[Not Useful Class, Useful Use Case, Not Useful..."
143,143,The clinic maintains a supplies inventory file...,"[Useful for Class Diagram, Useful for Use Case..."
144,144,Supplies and tools are stored in a standard la...,"[Useful Class, Not Useful Use Case, Not Useful..."

In [26]:
structure = []
usecase = []
activity = []
for index, item in r1_validated.iterrows():
    try:
        if "Not Useful Class" in item["Result"]:
            structure.append(False)
        elif "Not Useful for Class" in item["Result"]:
            structure.append(False)
        else:
            structure.append(True)
        if "Not Useful Use Case" in item["Result"]:
            usecase.append(False)
        elif "Not Useful for Use Case" in item["Result"]:
            usecase.append(False)
        else:
            usecase.append(True)
        if "Not Useful Activity" in item["Result"]:
            activity.append(False)
        elif "Not Useful for Activity" in item["Result"]:
            activity.append(False)
        else:
            activity.append(True)
    except:
        structure.append(False)
        usecase.append(False)
        activity.append(False)

r1_validated["structure"] = structure
r1_validated["usecase"] = usecase
r1_validated["activity"] = activity

In [27]:
r1_validated

,Unnamed: 0,Sentence,Result,structure,usecase,activity
0,0,Analyst : Do you run into any challenges with ...,"[Useful for Class Diagram, Not Useful for Use ...",True,False,False
1,1,"AP : Actually , that is a constant source of c...","[Not Useful Class, Not Useful Use Case, Not Us...",False,False,False
2,2,"We have had several situations where , due to ...","[Useful Class, Useful Use Case, Not Useful Act...",True,True,False
3,3,Analyst : Can you give me some examples of this ?,"[Useful Class, Useful Use Case, Not Useful Act...",True,True,False
4,4,AP :,It seems like the sentence is incomplete. Coul...,True,True,False
...,...,...,...,...,...,...
140,140,HMO - funded patients are asked to make a copa...,"[Useful Class, Useful Use Case, Not Useful Act...",True,True,False
141,141,Each patient also generates a reimbursement re...,"[Useful Class, Useful Use Case, Not Useful Act...",True,True,False
142,142,Insurance companies and HMOs send their checks...,"[Not Useful Class, Useful Use Case, Not Useful...",False,True,False
143,143,The clinic maintains a supplies inventory file...,"[Useful for Class Diagram, Useful for Use Case...",True,True,False
144,144,Supplies and tools are stored in a standard la...,"[Useful Class, Not Useful Use Case, Not Useful...",True,False,False

In [31]:
import pandas as pd
from sklearn.metrics import precision_score, recall_score, f1_score, accuracy_score

# Load ground truth and predictions
y_true = pd.read_csv("../type_classification-validation.csv")[["usecase_focus"]]
y_pred = r1_validated[["usecase"]]

# Compute evaluation metrics
precision = precision_score(y_true, y_pred, average='macro')
recall = recall_score(y_true, y_pred, average='macro')
f1 = f1_score(y_true, y_pred, average='macro')
accuracy = accuracy_score(y_true, y_pred)

print(f"Accuracy: {accuracy:.4f}")
print(f"Recall: {recall:.4f}")
print(f"Precision: {precision:.4f}")
print(f"F1-score: {f1:.4f}")

Accuracy: 0.6069
Recall: 0.7156
Precision: 0.6315
F1-score: 0.5745