In [22]:
import pandas as pd
from nltk import accuracy
from sklearn.metrics import classification_report

qwen25 = pd.read_csv("Qwen2.5-label-validation-15 example.csv")
qwen25

,Unnamed: 0,Sentence,Result
0,0,Analyst : Do you run into any challenges with ...,"Verdict: Not Useful for Class Diagram, Useful ..."
1,1,"AP : Actually , that is a constant source of c...","[Not Useful, Not Useful, Not Useful]"
2,2,"We have had several situations where , due to ...","Verdict: Not Useful for Class Diagram, Useful ..."
3,3,Analyst : Can you give me some examples of this ?,Certainly! Here are a few more sentences along...
4,4,AP :,"It seems you started a new sentence with ""AP :..."
...,...,...,...
140,140,HMO - funded patients are asked to make a copa...,"[Useful Class, Useful Use Case, Not Useful Act..."
141,141,Each patient also generates a reimbursement re...,"[Useful Class, Useful Use Case, Not Useful Act..."
142,142,Insurance companies and HMOs send their checks...,"[Useful Class, Useful Use Case, Not Useful Act..."
143,143,The clinic maintains a supplies inventory file...,"[Useful Class, Not Useful Use Case, Useful Act..."
144,144,Supplies and tools are stored in a standard la...,"Verdict: Useful for Class Diagram, Not Useful ..."

In [23]:
structure = []
usecase = []
activity = []
for index, item in qwen25.iterrows():
    try:
        if "Not Useful Class" in item["Result"]:
            structure.append(False)
        elif "Not Useful for Class" in item["Result"]:
            structure.append(False)
        else:
            structure.append(True)
        if "Not Useful Use Case" in item["Result"]:
            usecase.append(False)
        elif "Not Useful for Use Case" in item["Result"]:
            usecase.append(False)
        else:
            usecase.append(True)
        if "Not Useful Activity" in item["Result"]:
            activity.append(False)
        elif "Not Useful for Activity" in item["Result"]:
            activity.append(False)
        else:
            activity.append(True)
    except:
        structure.append(False)
        usecase.append(False)
        activity.append(False)

qwen25["structure"] = structure
qwen25["usecase"] = usecase
qwen25["activity"] = activity

In [24]:
qwen25

,Unnamed: 0,Sentence,Result,structure,usecase,activity
0,0,Analyst : Do you run into any challenges with ...,"Verdict: Not Useful for Class Diagram, Useful ...",False,True,False
1,1,"AP : Actually , that is a constant source of c...","[Not Useful, Not Useful, Not Useful]",True,True,True
2,2,"We have had several situations where , due to ...","Verdict: Not Useful for Class Diagram, Useful ...",False,True,False
3,3,Analyst : Can you give me some examples of this ?,Certainly! Here are a few more sentences along...,False,False,False
4,4,AP :,"It seems you started a new sentence with ""AP :...",True,True,True
...,...,...,...,...,...,...
140,140,HMO - funded patients are asked to make a copa...,"[Useful Class, Useful Use Case, Not Useful Act...",True,True,False
141,141,Each patient also generates a reimbursement re...,"[Useful Class, Useful Use Case, Not Useful Act...",True,True,False
142,142,Insurance companies and HMOs send their checks...,"[Useful Class, Useful Use Case, Not Useful Act...",True,True,False
143,143,The clinic maintains a supplies inventory file...,"[Useful Class, Not Useful Use Case, Useful Act...",True,False,True
144,144,Supplies and tools are stored in a standard la...,"Verdict: Useful for Class Diagram, Not Useful ...",True,False,False

In [27]:
import pandas as pd
from sklearn.metrics import precision_score, recall_score, f1_score, accuracy_score

# Load ground truth and predictions
y_true = pd.read_csv("../type_classification-validation.csv")[["process_focus"]]
y_pred = qwen25[["activity"]]

# Compute evaluation metrics
precision = precision_score(y_true, y_pred, average='macro')
recall = recall_score(y_true, y_pred, average='macro')
f1 = f1_score(y_true, y_pred, average='macro')
accuracy = accuracy_score(y_true, y_pred)

print(f"Precision: {precision:.4f}")
print(f"Recall: {recall:.4f}")
print(f"F1-score: {f1:.4f}")
print(f"Accuracy: {accuracy:.4f}")

Precision: 0.5471
Recall: 0.5615
F1-score: 0.5498
Accuracy: 0.7310