In [3]:
import pandas as pd
from nltk import accuracy
from sklearn.metrics import classification_report

gpt_validated = pd.read_csv("gpt4o-label-validation-15 example.csv")
gpt_validated.columns = ["index", "Sentence", "Result"]
gpt_validated

,index,Sentence,Result
0,0,Analyst : Do you run into any challenges with ...,"[Not Useful Class, Not Useful Use Case, Not Us..."
1,1,"AP : Actually , that is a constant source of c...","[Not Useful Class, Not Useful Use Case, Not Us..."
2,2,"We have had several situations where , due to ...","[Not Useful Class, Useful Use Case, Not Useful..."
3,3,Analyst : Can you give me some examples of this ?,"[Not Useful Class, Useful Use Case, Not Useful..."
4,4,AP :,"[Not Useful Class, Not Useful Use Case, Not Us..."
...,...,...,...
140,140,HMO - funded patients are asked to make a copa...,"[Not Useful Class, Useful Use Case, Useful Act..."
141,141,Each patient also generates a reimbursement re...,"[Useful Class, Useful Use Case, Not Useful Act..."
142,142,Insurance companies and HMOs send their checks...,"[Not Useful Class, Not Useful Use Case, Not Us..."
143,143,The clinic maintains a supplies inventory file...,"[Useful Class, Useful Use Case, Not Useful Act..."
144,144,Supplies and tools are stored in a standard la...,"[Useful Class, Not Useful Use Case, Not Useful..."

In [4]:
structure = []
usecase = []
activity = []
for index, item in gpt_validated.iterrows():
    if "Not Useful Class" in item["Result"]:
        structure.append(False)
    else:
        structure.append(True)
    if "Not Useful Use Case" in item["Result"]:
        usecase.append(False)
    else:
        usecase.append(True)
    if "Not Useful Activity" in item["Result"]:
        activity.append(False)
    else:
        activity.append(True)

gpt_validated["structure"] = structure
gpt_validated["usecase"] = usecase
gpt_validated["activity"] = activity

In [5]:
gpt_validated

,index,Sentence,Result,structure,usecase,activity
0,0,Analyst : Do you run into any challenges with ...,"[Not Useful Class, Not Useful Use Case, Not Us...",False,False,False
1,1,"AP : Actually , that is a constant source of c...","[Not Useful Class, Not Useful Use Case, Not Us...",False,False,False
2,2,"We have had several situations where , due to ...","[Not Useful Class, Useful Use Case, Not Useful...",False,True,False
3,3,Analyst : Can you give me some examples of this ?,"[Not Useful Class, Useful Use Case, Not Useful...",False,True,False
4,4,AP :,"[Not Useful Class, Not Useful Use Case, Not Us...",False,False,False
...,...,...,...,...,...,...
140,140,HMO - funded patients are asked to make a copa...,"[Not Useful Class, Useful Use Case, Useful Act...",False,True,True
141,141,Each patient also generates a reimbursement re...,"[Useful Class, Useful Use Case, Not Useful Act...",True,True,False
142,142,Insurance companies and HMOs send their checks...,"[Not Useful Class, Not Useful Use Case, Not Us...",False,False,False
143,143,The clinic maintains a supplies inventory file...,"[Useful Class, Useful Use Case, Not Useful Act...",True,True,False
144,144,Supplies and tools are stored in a standard la...,"[Useful Class, Not Useful Use Case, Not Useful...",True,False,False

In [9]:
import pandas as pd
from sklearn.metrics import precision_score, recall_score, f1_score, accuracy_score

# Load ground truth and predictions
y_true = pd.read_csv("../type_classification-validation.csv")[["process_focus"]]
y_pred = gpt_validated[["activity"]]

# Compute evaluation metrics
precision = precision_score(y_true, y_pred, average='macro')
recall = recall_score(y_true, y_pred, average='macro')
f1 = f1_score(y_true, y_pred, average='macro')
accuracy = accuracy_score(y_true, y_pred)

print(f"Precision: {precision:.4f}")
print(f"Recall: {recall:.4f}")
print(f"F1-score: {f1:.4f}")
print(f"Accuracy: {accuracy:.4f}")

Precision: 0.6983
Recall: 0.7199
F1-score: 0.7080
Accuracy: 0.8414